import type { Category, Product, Table } from "./types";

export const dataCategories: Category[] = [
  { id: "hamburguesas", name: "Hamburguesas" },
  { id: "pizzas", name: "Pizzas" },
  { id: "entradas", name: "Entradas" },
  { id: "postres", name: "Postres" },
  { id: "bebidas", name: "Bebidas" },
  { id: "cafes", name: "Cafés" },
  { id: "jugos", name: "Jugos" },
];

export const dataProducts: Product[] = [
  // COCINA
  {
    id: "p_clasica",
    name: "Clásica",
    description: "Medallón 120g, cheddar, lechuga, tomate y mayo.",
    priceCents: 9000,
    station: "cocina",
    categoryId: "hamburguesas",
  },
  {
    id: "p_doble_bacon",
    name: "Doble Bacon",
    description: "Dos medallones 120g, cheddar y bacon crocante.",
    priceCents: 12000,
    station: "cocina",
    categoryId: "hamburguesas",
  },
  {
    id: "p_barbacoa",
    name: "Barbacoa",
    description: "Medallón 120g, cheddar, cebolla caramelizada y salsa barbacoa.",
    priceCents: 10500,
    station: "cocina",
    categoryId: "hamburguesas",
  },
  {
    id: "p_pizza_margarita",
    name: "Margarita",
    description: "Mozzarella, salsa de tomate y albahaca.",
    priceCents: 11000,
    station: "cocina",
    categoryId: "pizzas",
  },
  {
    id: "p_pizza_pepperoni",
    name: "Pepperoni",
    description: "Mozzarella, salsa de tomate y pepperoni.",
    priceCents: 12500,
    station: "cocina",
    categoryId: "pizzas",
  },
  {
    id: "p_pizza_4quesos",
    name: "Cuatro Quesos",
    description: "Mozzarella, roquefort, parmesano y provolone.",
    priceCents: 13000,
    station: "cocina",
    categoryId: "pizzas",
  },
  {
    id: "p_papas",
    name: "Papas fritas",
    description: "Porción grande con sal marina.",
    priceCents: 5000,
    station: "cocina",
    categoryId: "entradas",
  },
  {
    id: "p_aros_cebolla",
    name: "Aros de cebolla",
    description: "Crujientes, con salsa barbacoa.",
    priceCents: 5500,
    station: "cocina",
    categoryId: "entradas",
  },
  {
    id: "p_rabas",
    name: "Rabas",
    description: "Con limón y alioli.",
    priceCents: 9000,
    station: "cocina",
    categoryId: "entradas",
  },
  {
    id: "p_flan",
    name: "Flan casero",
    description: "Con dulce de leche o crema.",
    priceCents: 4500,
    station: "cocina",
    categoryId: "postres",
  },
  {
    id: "p_brownie",
    name: "Brownie con helado",
    description: "Brownie tibio con bocha de americana.",
    priceCents: 6000,
    station: "cocina",
    categoryId: "postres",
  },
  // BAR
  {
    id: "p_cerveza",
    name: "Cerveza artesanal",
    description: "Pinta rubia o IPA.",
    priceCents: 4500,
    station: "bar",
    categoryId: "bebidas",
  },
  {
    id: "p_agua",
    name: "Agua mineral",
    description: "Botella 500ml, con o sin gas.",
    priceCents: 2000,
    station: "bar",
    categoryId: "bebidas",
  },
  {
    id: "p_gaseosa",
    name: "Gaseosa",
    description: "Lata 473ml.",
    priceCents: 2500,
    station: "bar",
    categoryId: "bebidas",
  },
  {
    id: "p_limonada",
    name: "Limonada",
    description: "Limonada con hierbabuena, 500ml.",
    priceCents: 3500,
    station: "bar",
    categoryId: "bebidas",
  },
  {
    id: "p_espresso",
    name: "Café expreso",
    description: "Simple.",
    priceCents: 2000,
    station: "bar",
    categoryId: "cafes",
  },
  {
    id: "p_cortado",
    name: "Cortado",
    description: "Con leche.",
    priceCents: 2200,
    station: "bar",
    categoryId: "cafes",
  },
  {
    id: "p_capuchino",
    name: "Capuchino",
    description: "Con canela.",
    priceCents: 2600,
    station: "bar",
    categoryId: "cafes",
  },
  {
    id: "p_naranja",
    name: "Jugo de naranja",
    description: "Exprimido, 400ml.",
    priceCents: 3000,
    station: "bar",
    categoryId: "jugos",
  },
  {
    id: "p_limon",
    name: "Jugo de limón",
    description: "Exprimido, 400ml.",
    priceCents: 3000,
    station: "bar",
    categoryId: "jugos",
  },
];

export const dataTables: Table[] = [
  { id: "t1", label: "Mesa 1", sector: "Sector A", status: "libre" },
  { id: "t2", label: "Mesa 2", sector: "Sector A", status: "libre" },
  { id: "t3", label: "Mesa 3", sector: "Sector A", status: "libre" },
  { id: "t4", label: "Mesa 4", sector: "Sector A", status: "libre" },
  { id: "t5", label: "Mesa 5", sector: "Sector B", status: "libre" },
  { id: "t6", label: "Mesa 6", sector: "Sector B", status: "libre" },
  { id: "t7", label: "Mesa 7", sector: "Sector B", status: "libre" },
  { id: "t8", label: "Mesa 8", sector: "Sector B", status: "libre" },
];
